runtime: php55
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /facebook\.png
  static_files: facebook.png
  
- url: /favicon\.ico
  static_files: favicon.ico
  
- url: /style\.css
  static_files: style.css

- url: /main\.js
  static_files: main.js
  
- url: /main\.php
  script: main.php
  
- url: /*
  script: index.html